# 圆形机器人半径大小
# robot_radius: 0.5

# 多边形机器人边界
footprint: [[-0.46, -0.233], [-0.46, 0.233], [0.1, 0.233], [0.1, -0.233]]
footprint_padding: 0.05

# 机器人与障碍物之间必须保持的最小距离
inflation_radius: 0.15

# 传感器的最大探测距离
obstacle_range: 5.5
raytrace_range: 6.0

# 传感器读取最大高度被视为有效
max_obstacle_height: 0.6
min_obstacle_height: 0.0

# 导航功能包集所使用的传感器
observation_sources: laser
laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, , expected_update_rate: 0, inf_is_valid: true}


# robot_base_frame: base_link
# update_frequency: 4.0
# publish_frequency: 2.0
# transform_tolerance: 0.5

# resolution: 0.05

# static:
#     map_topic: /map
#     subscribe_to_updates: true