# 圆形机器人半径大小
# robot_radius: 0.5

# 多边形机器人边界
footprint: [[-0.46, -0.23], [-0.46, 0.23], [0.1, 0.23], [0.1, -0.23]]
footprint_padding: 0.01

# 传感器的最大探测距离
obstacle_range: 5.5
raytrace_range: 6.0

# 传感器读取最大高度被视为有效
# max_obstacle_height: 0.6
# min_obstacle_height: 0.1


# 机器人参考坐标
robot_base_frame: base_link

# 基于传感器数据更新局部地图的频率
update_frequency: 3.0

# 发布信息的频率
publish_frequency: 1.0

# 在tf树坐标之间转换的允许延时或者绘图过程临时被中止的允许延时 (s)
transform_tolerance: 0.5

# 导航功能包集所使用的传感器
obstacles:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, expected_update_rate: 0, inf_is_valid: true}

static:
  map_topic: /map
  subscribe_to_updates: true

# 机器人与障碍物之间必须保持的最小距离
inflation:
  inflation_radius: 1.0