global_costmap:

  # 全局代价地图，使用/map作为全局坐标
  global_frame: /map

  # 两种类型：voxel 和 costmap，voxel 表示3D视图，costmap 表示2D视图
  map_type: costmap

  # 机器人参考坐标
  robot_base_frame: /base_link

  # 基于传感器数据更新局部地图的频率
  update_frequency: 4.0

  # 发布信息的频率
  publish_frequency: 2.0

  # 在tf树坐标之间转换的允许延时或者绘图过程临时被中止的允许延时 (s)
  transform_tolerance: 0.5

  # 分辨率
  resolution: 0.05

  # 是否使用先验地图
  static_map: true

  # rolling_window用于配置在机器人运动过程中，代价地图始终以机器人为中心
  rolling_window: false


