global_costmap:

  # 全局代价地图，使用/odom作为全局坐标
  global_frame: odom

  track_unknown_space: true
  
  # rolling_window用于配置在机器人运动过程中，代价地图始终以机器人为中心
  rolling_window: true
  
  # 两种类型：voxel 和 costmap，voxel 表示3D视图，costmap 表示2D视图
  # map_type: costmap

  # 分辨率
  resolution: 0.05
  
  plugins:
    -{name: obstacles,  type:"costmap_2d::ObstacleLayer"}
    -{name: inflation,  type:"costmap_2d::InflationLayer"}

